serverURL: http://localhost:8080
apiKey: fake
minVolume: 450
vadEnabled: true
vadModelPath: /models/silero_vad.onnx
sttModel: whisper-1
chatModel: qwen3-4b

ttsModel: voice-en-us-amy-low
temperature: 0.7
wakeWord: Computer

introPrompt: Initially, start the conversation by asking the user how you can help them and explain that she must say '{wakeWord}' in order to address you.

prompt:
- &basePrompt |
  You are a helpful assistant.
  Your name is {wakeWord}.
  You are interacting with the user via STT and TTS technology. Therefore don't output Markdown or emoticons.

#You must speak to the user using the 'say' function. Before and after calling any other function, call the 'say' function to tell the user what you're doing!
#In case the user asks you to use an external tool, confirm the action by saying e.g. 'Okay.'.
#In case the user asks you to use an external tool, provide a short confirming response such as 'Okay.' followed by '%[2]s' on a new line followed by a prompt for another AI with tool access to finish the response.
#You can access external tools as well as the internet by returning a prompt after an intermediate response as quick user feedback, separated by '%[2]s' on a new line.
#To use an external tool or access the internet, end your response with a new line followed by '%[2]s' followed by the prompt that will fed into another AI with tool access to answer the user request on your behalf.
#systemPrompt := "Du bist ein hilfreicher Assistent. Antworte kurz, bündig und auf deutsch!"

mcpServers:
  tool-containers:
    command: /tool-containers-mcp
    args:
      - --config=/etc/tool-containers-mcp/tools.yaml

tools:
- mcpServer: tool-containers
  #allow:
  #- wikipedia
