FROM golang:1.26-alpine3.23 AS server
COPY go.mod go.sum /build/
WORKDIR /build
RUN go mod download
COPY cmd/ai-assistant-vui-server /build/cmd/ai-assistant-vui-server
COPY internal /build/internal
COPY pkg /build/pkg
ENV CGO_ENABLED=0
RUN go build -o ai-assistant-vui-server -ldflags '-s -w -extldflags "-static"' ./cmd/ai-assistant-vui-server

FROM node:24-alpine3.23 AS ui
COPY ui/package.json ui/package-lock.json /ui/
WORKDIR /ui
RUN npm install
COPY ui /ui
RUN npm run build

FROM mgoltzsche/tool-containers-mcp:0.1.0 AS tool-containers

FROM alpine:3.23
ENV VUI_LOG_LEVEL=DEBUG
COPY --from=server /build/ai-assistant-vui-server /
COPY config.yaml /etc/ai-assistant-vui/config.yaml
COPY --from=ui /ui/dist /var/lib/ai-assistant-vui/ui
COPY --from=tool-containers /tool-containers-mcp /
COPY tools.yaml /etc/tool-containers-mcp/
# To test whether tools.yaml is valid (mcp client doesn't return errors)
#RUN /tool-containers-mcp --config=/etc/tool-containers-mcp/tools.yaml
ENTRYPOINT ["/ai-assistant-vui-server"]
